site_name: Course Explorer Documentation
site_url: https://documentation.course-explorer.com/
nav:
  - Home: index.md
  - Dokumentation:
    - Präsenzkurse: documentation/courses/presencecourses.md
    - Onlinekurse: documentation/courses/onlinecourses.md
    - Benutzermanagement: documentation/user-management/index.md
    - Reiseantrag: documentation/travel-request/index.md
    - Konfiguration: documentation/configuration/index.md

theme:
  name: material
  language: de
  logo: img/logo.svg
  favicon: img/favicon.ico
  palette: 
    - media: "(prefers-color-scheme: light)" 
      scheme: courseexplorer
      primary: blue
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2022 Second To None GmbH
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /
      lang: de
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg